const BraceletDetailsActionTypes = {
    BRACELET_DETAILS_REQUEST_START: 'BRACELET_DETAILS_REQUEST_START',
    BRACELET_DETAILS_REQUEST_SUCCESS: 'BRACELET_DETAILS_REQUEST_SUCCESS',
    BRACELET_DETAILS_REQUEST_FAIL: 'BRACELET_DETAILS_REQUEST_FAIL',
    ADD_BRACELET_DETAILS_REQUEST_SUCCESS: 'ADD_BRACELET_DETAILS_REQUEST_SUCCESS',
    UPDATE_BRACELET_DETAILS_REQUEST_SUCCESS: 'UPDATE_BRACELET_DETAILS_REQUEST_SUCCESS',
    BRACELET_DETAILS_PAGE_RESET: 'BRACELET_DETAILS_PAGE_RESET',
    BRACELET_DETAILS_POPUP_BOX_ERROR_MESSAGE: 'BRACELET_DETAILS_POPUP_BOX_ERROR_MESSAGE',
    SET_BRACELET_DETAILS: 'SET_BRACELET_DETAILS',
    VALIDATE_BRACELET_DETAILS: 'VALIDATE_BRACELET_DETAILS',
    DELETE_BRACELET_REQUEST_SUCCESS: 'DELETE_BRACELET_REQUEST_SUCCESS',
    DELETE_BRACELET_INFO_MSG: 'DELETE_BRACELET_INFO_MSG'

};

export default BraceletDetailsActionTypes;