const GroupBraceletsActionTypes = {
    BRACELETS_REQUEST_START: 'BRACELETS_REQUEST_START',
    BRACELETS_REQUEST_SUCCESS: 'BRACELETS_REQUEST_SUCCESS',
    BRACELETS_REQUEST_FAIL: 'BRACELETS_REQUEST_FAIL',
    ADD_BRACELETS_REQUEST_SUCCESS: 'ADD_BRACELETS_REQUEST_SUCCESS',
    SET_BRACELETS_ALPHABET_VAL: 'SET_BRACELETS_ALPHABET_VAL',
    SET_BRACELETS_GROUP_ID_VAL: 'SET_BRACELETS_GROUP_ID_VAL',
    BRACELETS_PAGE_RESET: 'BRACELETS_PAGE_RESET',
    BRACELETS_POPUP_BOX_ERROR_MESSAGE: 'BRACELETS_POPUP_BOX_ERROR_MESSAGE',
    BRACELET_SEARCH: "BRACELET_SEARCH"
};

export default GroupBraceletsActionTypes;