const ClientsActionTypes = {
    CLIENTS_REQUEST_START: 'CLIENTS_REQUEST_START',
    CLIENTS_REQUEST_SUCCESS: 'CLIENTS_REQUEST_SUCCESS',
    CLIENTS_REQUEST_FAIL: 'CLIENTS_REQUEST_FAIL',
    ADD_CLIENTS_REQUEST_SUCCESS: 'ADD_CLIENTS_REQUEST_SUCCESS',
    SET_CLIENTS_ALPHABET_VAL: 'SET_CLIENTS_ALPHABET_VAL',
    FIND_STATE_BY_CLIENT: 'FIND_STATE_BY_CLIENT',
    CLIENT_PAGE_RESET: "CLIENT_PAGE_RESET",
    POPUP_BOX_ERROR_MESSAGE: 'POPUP_BOX_ERROR_MESSAGE',
};

export default ClientsActionTypes;