const ClientDetailsActionTypes = {
    CLIENT_DETAILS_REQUEST_START: 'CLIENT_DETAILS_REQUEST_START',
    CLIENT_DETAILS_REQUEST_SUCCESS: 'CLIENT_DETAILS_REQUEST_SUCCESS',
    CLIENT_DETAILS_REQUEST_FAIL: 'CLIENT_DETAILS_REQUEST_FAIL',
    CLIENT_USER_EXISTS_FAIL: 'CLIENT_USER_EXISTS_FAIL',
    ADD_CLIENT_DETAILS_REQUEST_SUCCESS: 'ADD_CLIENT_DETAILS_REQUEST_SUCCESS',
    UPDATE_CLIENT_DETAILS_REQUEST_SUCCESS: 'UPDATE_CLIENT_DETAILS_REQUEST_SUCCESS',
    SET_CLIENT_DETAILS_GROUP_ID_VAL: 'SET_CLIENT_DETAILS_GROUP_ID_VAL',
    CLIENT_DETAILS_PAGE_RESET: 'CLIENT_DETAILS_PAGE_RESET',
    CLIENT_DETAILS_POPUP_BOX_ERROR_MESSAGE: 'CLIENT_DETAILS_POPUP_BOX_ERROR_MESSAGE',
    SET_CLIENT_DETAILS: 'SET_CLIENT_DETAILS',
    SET_CLIENT_USERS_DETAILS: 'SET_CLIENT_USERS_DETAILS',
    ADD_MORE_USERS: 'ADD_MORE_USERS',
    VALIDATE_CLIENT_DETAILS: 'VALIDATE_CLIENT_DETAILS',
    UPDATE_CLIENT_USER_PASSWORD: 'UPDATE_CLIENT_USER_PASSWORD',
    EDIT_PASSWORD_USER: 'EDIT_PASSWORD_USER',
    CLIENT_USERNAME_EXIST: 'CLIENT_USERNAME_EXIST',
    DELETE_CLIENT_REQUEST_SUCCESS: 'DELETE_CLIENT_REQUEST_SUCCESS'

};

export default ClientDetailsActionTypes;