const DepartmentActionTypes = {
    DEPARTMENTS_REQUEST_START: 'DEPARTMENTS_REQUEST_START',
    DEPARTMENTS_REQUEST_SUCCESS: 'DEPARTMENTS_REQUEST_SUCCESS',
    DEPARTMENTS_REQUEST_FAIL: 'DEPARTMENTS_REQUEST_FAIL',
    ADD_DEPARTMENTS_REQUEST_SUCCESS: 'ADD_DEPARTMENTS_REQUEST_SUCCESS',
    SET_DEPARTMENT_ALPHABET_VAL: 'SET_DEPARTMENT_ALPHABET_VAL',
    PAGE_RESET_DEPARTMENT: 'PAGE_RESET_DEPARTMENT',

    POPUP_BOX_ERROR_MESSAGE: 'PAGE_RESET',
};

export default DepartmentActionTypes;