const DepartmentDetailsActionTypes = {
    DEPARTMENT_DETAILS_REQUEST_START: 'DEPARTMENT_DETAILS_REQUEST_START',
    DEPARTMENT_DETAILS_REQUEST_SUCCESS: 'DEPARTMENT_DETAILS_REQUEST_SUCCESS',
    DEPARTMENT_DETAILS_REQUEST_FAIL: 'DEPARTMENT_DETAILS_REQUEST_FAIL',
    DEPARTMENT_DETAILS_SEARCH: 'DEPARTMENT_DETAILS_SEARCH',
    DEPARTMENT_DETAILS_ID: 'DEPARTMENT_DETAILS_ID',
    ADD_DEPARTMENT_DETAILS_REQUEST_SUCCESS: "ADD_DEPARTMENT_DETAILS_REQUEST_SUCCESS",
    ADD_DEPARTMENT_DETAILS_REQUEST_FAIL: "ADD_DEPARTMENT_DETAILS_REQUEST_FAIL",
    EMPTY_FIELDS_ON_LOAD: 'EMPTY_FIELDS_ON_LOAD',
    SET_DEPARTMENT_FORM_DETAILS: 'SET_DEPARTMENT_FORM_DETAILS',
    DEPARTMENT_EDIT_CREATE_POPUP_BOX_ERROR_MESSAGE: 'DEPARTMENT_EDIT_CREATE_POPUP_BOX_ERROR_MESSAGE',
    ACTIVE_TAB: 'ACTIVE_TAB',
    UPDATE_DEPARTMENT_DETAILS_REQUEST_SUCCESS: "UPDATE_DEPARTMENT_DETAILS_REQUEST_SUCCESS",
    RELOAD_DEPARTMENT_DETAILS: "RELOAD_DEPARTMENT_DETAILS",
    DELETE_DEPARTMENT_REQUEST_SUCCESS: 'DELETE_DEPARTMENT_REQUEST_SUCCESS',
    DELETE_DEPARTMENT_INFO_MSG: 'DELETE_DEPARTMENT_INFO_MSG'
};

export default DepartmentDetailsActionTypes;
