const EditHomeScreenActionTypes = {
    EDITHOMESCREEN_REQUEST_START: 'EDITHOMESCREEN_REQUEST_START',
    EDITHOMESCREENS_REQUEST_SUCCESS: 'EDITHOMESCREENS_REQUEST_SUCCESS',
    EDITHOMESCREENS_REQUEST_FAIL: 'EDITHOMESCREENS_REQUEST_FAIL',
    ADD_EVENT_HOMESCREENS_REQUEST_SUCCESS: 'ADD_EVENT_HOMESCREENS_REQUEST_SUCCESS',
    REMOVE_EVENT_EDITHOMESCREENS_REQUEST_SUCCESS: 'REMOVE_EVENT_EDITHOMESCREENS_REQUEST_SUCCESS',
    EDIT_HOME_SCREEN_CLEAR_DATA: 'EDIT_HOME_SCREEN_CLEAR_DATA'
};

export default EditHomeScreenActionTypes;