const EventsActionTypes = {
    EVENTS_REQUEST_START: 'EVENTS_REQUEST_START',
    EVENTS_REQUEST_SUCCESS: 'EVENTS_REQUEST_SUCCESS',
    EVENTS_REQUEST_FAIL: 'EVENTS_REQUEST_FAIL',
    ADD_EVENTS_REQUEST_SUCCESS: 'ADD_EVENTS_REQUEST_SUCCESS',
    EVENTS_TYPES_SUCCESS: 'EVENTS_TYPES_SUCCESS',
    SET_EVENTS_ALPHABET_VAL: 'SET_EVENTS_ALPHABET_VAL',
    SET_EVENTS_GROUP_ID_VAL: 'SET_EVENTS_GROUP_ID_VAL',
    EVENTS_PAGE_RESET: 'EVENTS_PAGE_RESET',
    EVENTS_POPUP_BOX_ERROR_MESSAGE: 'EVENTS_POPUP_BOX_ERROR_MESSAGE',
    EVENT_SEARCH: "EVENT_SEARCH",
    SET_CURRENT_DATE: "SET_CURRENT_DATE",
    RESET_EVENTS_DATA: "RESET_EVENTS_DATA",
    SET_EVENT_TYPE: "SET_EVENT_TYPE"
};

export default EventsActionTypes;