const GroupDetilsActionTypes = {
    GROUP_DETAILS_REQUEST_START: 'GROUP_DETAILS_REQUEST_START',
    GROUP_DETAILS_REQUEST_SUCCESS: 'GROUP_DETAILS_REQUEST_SUCCESS',
    GROUP_DETAILS_REQUEST_FAIL: 'GROUP_DETAILS_REQUEST_FAIL',
    GROUP_DETAILS_SEARCH: 'GROUP_DETAILS_SEARCH',
    GROUP_DETAILS_ID: 'GROUP_DETAILS_ID',
    ADD_GROUP_DETAILS_REQUEST_SUCCESS: "ADD_GROUP_DETAILS_REQUEST_SUCCESS",
    ADD_GROUP_DETAILS_REQUEST_FAIL: "ADD_GROUP_DETAILS_REQUEST_FAIL",
    EMPTY_FIELDS_ON_LOAD: 'EMPTY_FIELDS_ON_LOAD',
    SET_GROUP_FORM_DETAILS: 'SET_GROUP_FORM_DETAILS',
    GROUP_EDIT_CREATE_POPUP_BOX_ERROR_MESSAGE: 'GROUP_EDIT_CREATE_POPUP_BOX_ERROR_MESSAGE',
    ACTIVE_TAB: 'ACTIVE_TAB',
    UPDATE_GROUP_DETAILS_REQUEST_SUCCESS: "UPDATE_GROUP_DETAILS_REQUEST_SUCCESS",
    RELOAD_GROUP_DETAILS: "RELOAD_GROUP_DETAILS",
    DELETE_GROUP_REQUEST_SUCCESS: 'DELETE_GROUP_REQUEST_SUCCESS',
    DELETE_GROUP_INFO_MSG: 'DELETE_GROUP_INFO_MSG'
};

export default GroupDetilsActionTypes;