const GroupSupervisorActionTypes = {
    REQUEST_START: 'REQUEST_START',
    REQUEST_SUCCESS: 'REQUEST_SUCCESS',
    REQUEST_FAIL: 'REQUEST_FAIL',
    SEARCH: 'SEARCH',

    PAGEINATION_NEXT_PAGE: 'PAGEINATION_NEXT_PAGE',
    PAGEINATION_PREVIOUS_PAGE: 'PAGEINATION_PREVIOUS_PAGE',
    PAGENATION_TOTAL_PAGES: 'PAGENATION_TOTAL_PAGES',
};

export default GroupSupervisorActionTypes;