const GroupsActionTypes = {
    GROUPS_REQUEST_START: 'GROUPS_REQUEST_START',
    GROUPS_REQUEST_SUCCESS: 'GROUPS_REQUEST_SUCCESS',
    GROUPS_REQUEST_FAIL: 'GROUPS_REQUEST_FAIL',
    ADD_GROUPS_REQUEST_SUCCESS: 'ADD_GROUPS_REQUEST_SUCCESS',
    SET_GROUP_ALPHABET_VAL: 'SET_GROUP_ALPHABET_VAL',
    PAGE_RESET_GROUP: 'PAGE_RESET_GROUP',

    POPUP_BOX_ERROR_MESSAGE: 'PAGE_RESET',
};

export default GroupsActionTypes;