const HomePageActionTypes = {
    HOME_PAGE_REQUEST_START: 'HOME_PAGE_REQUEST_START',
    HOME_PAGE_REQUEST_SUCCESS: 'HOME_PAGE_REQUEST_SUCCESS',
    HOME_PAGE_REQUEST_FAIL: 'HOME_PAGE_REQUEST_FAIL',
    HOME_PAGE_PERCENTAGE_REQUEST_FAIL: 'HOME_PAGE_PERCENTAGE_REQUEST_FAIL',
    ALL_EVETNS_REQUEST_SUCCESS: 'ALL_EVETNS_REQUEST_SUCCESS',
    SEARCH: 'SEARCH',

    EVENTS_PAGEINATION_NEXT_PAGE: 'EVENTS_PAGEINATION_NEXT_PAGE',
    EVENTS_PAGEINATION_PREVIOUS_PAGE: 'EVENTS_PAGEINATION_PREVIOUS_PAGE',

    HOME_PAGE_RESET: 'HOME_PAGE_RESET',
    POPUP_BOX_ERROR_MESSAGE: 'POPUP_BOX_ERROR_MESSAGE',
    HOME_PAGE_OVERVIEW: 'HOME_PAGE_OVERVIEW',
    PAGENATION_TOTAL_PAGES: 'PAGENATION_TOTAL_PAGES',
    HOME_PAGE_OFFENDERS_SUCCESS: 'HOME_PAGE_OFFENDERS_SUCCESS',
    HOME_PAGE_OFFENDERS_REQUEST_FAIL: 'HOME_PAGE_OFFENDERS_REQUEST_FAIL',
    SET_HOME_PAGE_DATA: 'SET_HOME_PAGE_DATA'

};

export default HomePageActionTypes;