const OffendersActionTypes = {
    OFFENDERS_REQUEST_START: 'OFFENDERS_REQUEST_START',
    OFFENDERS_REQUEST_SUCCESS: 'OFFENDERS_REQUEST_SUCCESS',
    OFFENDERS_REQUEST_FAIL: 'OFFENDERS_REQUEST_FAIL',
    ADD_OFFENDERS_REQUEST_SUCCESS: 'ADD_OFFENDERS_REQUEST_SUCCESS',
    SET_OFFENDERS_ALPHABET_VAL: 'SET_OFFENDERS_ALPHABET_VAL',
    SET_OFFENDERS_GROUP_ID_VAL: 'SET_OFFENDERS_GROUP_ID_VAL',
    OFFENDERS_PAGE_RESET: 'OFFENDERS_PAGE_RESET',
    SET_OFFENDERS_TYPE: 'SET_OFFENDERS_TYPE',
    SET_OFFENDERS_STATUS: 'SET_OFFENDERS_STATUS',


    OFFENDERS_POPUP_BOX_ERROR_MESSAGE: 'OFFENDERS_POPUP_BOX_ERROR_MESSAGE',
};

export default OffendersActionTypes;