const PlacesAutoCompleteActionTypes = {
    PLACES_LOADING_START: 'PLACES_LOADING_LIST',
    PLACES_REQEST_START: 'PLACES_REQEST_START',
    PLACES_REQEST_STOP: 'PLACES_REQEST_STOP',
    SET_PLACES_LIST: 'SET_PLACES_LIST',
    GET_LAT_LANG_BY_PLACE_ID: 'GET_LAT_LANG_BY_PLACE_ID',
    ON_CHANGE_ADDRESS: 'ON_CHANGE_ADDRESS',
};

export default PlacesAutoCompleteActionTypes;