const PrecinctsDetailsActionTypes = {
    PRECINCT_DETAILS_REQUEST_START: 'PRECINCT_DETAILS_REQUEST_START',
    PRECINCT_DETAILS_REQUEST_SUCCESS: 'PRECINCT_DETAILS_REQUEST_SUCCESS',
    PRECINCT_DETAILS_REQUEST_FAIL: 'PRECINCT_DETAILS_REQUEST_FAIL',
    ADD_PRECINCT_DETAILS_REQUEST_SUCCESS: 'ADD_PRECINCT_DETAILS_REQUEST_SUCCESS',
    UPDATE_PRECINCT_DETAILS_REQUEST_SUCCESS: 'UPDATE_PRECINCT_DETAILS_REQUEST_SUCCESS',
    SET_PRECINCT_DETAILS_GROUP_ID_VAL: 'SET_PRECINCT_DETAILS_GROUP_ID_VAL',
    PRECINCT_DETAILS_PAGE_RESET: 'PRECINCT_DETAILS_PAGE_RESET',
    PRECINCT_DETAILS_POPUP_BOX_ERROR_MESSAGE: 'PRECINCT_DETAILS_POPUP_BOX_ERROR_MESSAGE',
    SET_PRECINCT_DETAILS: 'SET_PRECINCT_DETAILS',
    VALIDATE_PRECINCT_DETAILS: 'VALIDATE_PRECINCT_DETAILS',
    PRECINCT_PAGE_GROUP_ID: 'PRECINCT_PAGE_GROUP_ID',
    PRECINCT_SET_NAV_FROM: 'PRECINCT_SET_NAV_FROM',
};

export default PrecinctsDetailsActionTypes;