const SupervisorActionTypes = {
    PRECINCTS_REQUEST_START: 'PRECINCTS_REQUEST_START',
    PRECINCTS_REQUEST_SUCCESS: 'PRECINCTS_REQUEST_SUCCESS',
    PRECINCTS_REQUEST_FAIL: 'PRECINCTS_REQUEST_FAIL',
    ADD_PRECINCTS_REQUEST_SUCCESS: 'ADD_PRECINCTS_REQUEST_SUCCESS',
    SET_PRECINCTS_ALPHABET_VAL: 'SET_PRECINCTS_ALPHABET_VAL',
    SET_PRECINCTS_GROUP_ID_VAL: 'SET_PRECINCTS_GROUP_ID_VAL',
    PRECINCTS_PAGE_RESET: 'PRECINCTS_PAGE_RESET',

    PRECINCTS_POPUP_BOX_ERROR_MESSAGE: 'PRECINCTS_POPUP_BOX_ERROR_MESSAGE',
};

export default SupervisorActionTypes;