const ResetPasswordActionTypes = {
    ON_RESET_PASSWORD_REQUEST_START: 'RESET_PASSWORD_REQUEST_START',
    ON_RESET_PASSWORD_REQUEST_SUCCESS: 'RESET_PASSWORD_REQUEST_SUCCESS',
    ON_RESET_PASSWORD_REQUEST_FAIL: 'RESET_PASSWORD_REQUEST_FAIL',
    ON_RESET_PASSWORD_FORM_CLEAR: 'RESET_PASSWORD_FORM_CLEAR',
    RESET_PASSWORD_ERROR_MSG: 'RESET_PASSWORD_ERROR_MSG',

    RESET_PASSWORD_POPUP_ERROR_MSG: 'RESET_PASSWORD_POPUP_ERROR_MSG',
    SET_RESET_PASSWORD_DETAILS: 'SET_RESET_PASSWORD_DETAILS',

};

export default ResetPasswordActionTypes;