const SupervisorDetailsActionTypes = {
    SUPERVISOR_DETAILS_REQUEST_START: 'SUPERVISOR_DETAILS_REQUEST_START',
    SUPERVISOR_DETAILS_REQUEST_SUCCESS: 'SUPERVISOR_DETAILS_REQUEST_SUCCESS',
    SUPERVISOR_DETAILS_REQUEST_FAIL: 'SUPERVISOR_DETAILS_REQUEST_FAIL',
    ADD_SUPERVISOR_DETAILS_REQUEST_SUCCESS: 'ADD_SUPERVISOR_DETAILS_REQUEST_SUCCESS',
    DELETE_SUPERVISOR_REQUEST_SUCCESS: 'DELETE_SUPERVISOR_REQUEST_SUCCESS',
    UPDATE_SUPERVISOR_DETAILS_REQUEST_SUCCESS: 'UPDATE_SUPERVISOR_DETAILS_REQUEST_SUCCESS',
    SET_SUPERVISOR_DETAILS_GROUP_ID_VAL: 'SET_SUPERVISOR_DETAILS_GROUP_ID_VAL',
    SUPERVISOR_DETAILS_PAGE_RESET: 'SUPERVISOR_DETAILS_PAGE_RESET',
    SUPERVISOR_DETAILS_POPUP_BOX_ERROR_MESSAGE: 'SUPERVISOR_DETAILS_POPUP_BOX_ERROR_MESSAGE',
    SET_SUPERVISOR_DETAILS: 'SET_SUPERVISOR_DETAILS',
    VALIDATE_SUPERVISOR_DETAILS: 'VALIDATE_SUPERVISOR_DETAILS',
    SUPERVISOR_PAGE_GROUP_ID: 'SUPERVISOR_PAGE_GROUP_ID',
    SUPERVISOR_SET_NAV_FROM: 'SUPERVISOR_SET_NAV_FROM',
    DELETE_SUPERVISOR_INFO_MSG: 'DELETE_SUPERVISOR_INFO_MSG',
    UPDATE_SUPERVISOR_PIC_INFO: 'UPDATE_SUPERVISOR_PIC_INFO',
    RE_ASSIGN_SUPERVISOR: 'RE_ASSIGN_SUPERVISOR',
    RE_ASSIGN_SUPERVISOR_SUCCESS: 'RE_ASSIGN_SUPERVISOR_SUCCESS',
};

export default SupervisorDetailsActionTypes;