const SupervisorActionTypes = {
    SUPERVISORS_REQUEST_START: 'SUPERVISORS_REQUEST_START',
    SUPERVISORS_REQUEST_SUCCESS: 'SUPERVISORS_REQUEST_SUCCESS',
    SUPERVISORS_REQUEST_FAIL: 'SUPERVISORS_REQUEST_FAIL',
    ADD_SUPERVISORS_REQUEST_SUCCESS: 'ADD_SUPERVISORS_REQUEST_SUCCESS',
    SET_SUPERVISORS_ALPHABET_VAL: 'SET_SUPERVISORS_ALPHABET_VAL',
    SET_SUPERVISORS_GROUP_ID_VAL: 'SET_SUPERVISORS_GROUP_ID_VAL',
    SUPERVISORS_PAGE_RESET: 'SUPERVISORS_PAGE_RESET',

    SUPERVISORS_POPUP_BOX_ERROR_MESSAGE: 'SUPERVISORS_POPUP_BOX_ERROR_MESSAGE',
};

export default SupervisorActionTypes;