const VictimsActionTypes = {
    VICTIMS_REQUEST_START: 'VICTIMS_REQUEST_START',
    VICTIMS_REQUEST_SUCCESS: 'VICTIMS_REQUEST_SUCCESS',
    VICTIMS_REQUEST_FAIL: 'VICTIMS_REQUEST_FAIL',
    ADD_VICTIMS_REQUEST_SUCCESS: 'ADD_VICTIMS_REQUEST_SUCCESS',
    SET_VICTIMS_ALPHABET_VAL: 'SET_VICTIMS_ALPHABET_VAL',
    SET_VICTIMS_GROUP_ID_VAL: 'SET_VICTIMS_GROUP_ID_VAL',
    VICTIMS_PAGE_RESET: 'VICTIMS_PAGE_RESET',
    VICTIMS_POPUP_BOX_ERROR_MESSAGE: 'VICTIMS_POPUP_BOX_ERROR_MESSAGE',
};

export default VictimsActionTypes;